config/routes.rb
Moza::Application.routes.draw do

  root :to => "welcome#index"
  devise_for :users, :skip => [:sessions], :controllers => { :registrations => :user_registrations }

  resources :users, :only => [:show, :index]

  resources :users do 

    member do
      get :following, :followers
    end

    resources :comments

  end

  as :user do
    get "account-artist" => "users#artist",            :as => :account_type_artist
    get "account-fan"    => "users#fan",               :as => :account_type_fan
    get 'account-type'   => 'users#type',              :as => :account_type
    get 'signin'         => 'devise/sessions#new',     :as => :new_user_session
    post 'signin'        => 'devise/sessions#create',  :as => :user_session
    delete 'signout'     => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :relationships, only: [:create, :destroy]
  
  resources :playlists do 
    resources :comments
    member { get :add_song_to }
  end
  
  resources :galleries do
    resources :comments
    resources :images
  end

  resources :images do
    resources :comments
  end

  namespace :admin do
    get 'home' => "pages#home"
  end

  resources :events do
    resources :comments
  end

  resources :videos do
    resources :comments
  end

  resources :albums do
    member { get :vote }

    resources :comments
    resources :songs
  end

  resources :songs do 
    member { 
      get :buy
      get :vote 
    }
  end
  
  resources :genres
  resources :articles

  match "discover" => "discover#index"
  match "discover/browse" => "discover#browse"
  match 'restricted' => "exceptions#restricted", :as => :restricted
  match 'buy/song/paypal' => "pages#paypal", :as => :paypal

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :user
	has_many :songs
	has_many :comments, as: :commentable, :dependent => :destroy

	has_reputation :album_votes, source: :user, aggregated_by: :sum
	has_reputation :song_votes, source: {reputation: :song_votes, of: :songs}, aggregated_by: :sum

	attr_accessible :active, :description, :featured, :name, :position, :record_label, :year_produced, :cover
	
	validates :record_label, 
			  allow_blank: true,
	          length: { 
	            minimum: 2, maximum: 40, 
	            :message => "2-40 characters." 
	          }

	validates :name,
	          presence: true,
	          length: {
	            minimum: 2, maximum: 40,
	            :message => "2-40 characters."
	          }

	validates :description,
	          allow_blank: true,
	          length: {
	            minimum: 2, maximum: 500,
	            :message => "2-500 characters."
	          }

	validates_numericality_of :year_produced, :only_integer => true, :message => "can only be whole number."

	validates_inclusion_of :year_produced, :in => 1900..2099, :message => "can only be between 1900 and 2099."

	has_attached_file :cover, 
                      :styles => {
                        :small => "150x150#", 
                        :full_small => "150x150>", 
                        :medium => "400x400#", 
                        :full_medium => "400x400>", 
                        :large => "900x900#", 
                        :full_large => "900x900>",
                        :avatar => "60x60#"
                      },
			  		  :storage => :s3,
					  :s3_credentials => "#{Rails.root}/config/s3.yml",
                      default_url: 'http://placehold.it/400x400'

	include PgSearch
	pg_search_scope :search, 
							against: [:name, :record_label],
							using: {tsearch: {dictionary: "english"}},
							associated_against: {user: :artist_name, songs: :name}

	def self.text_search(query)
		if query.present?
			search(query)
		else
			scoped
		end
	end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

	load_and_authorize_resource
	
	def vote
		value = params[:type] == "up" ? 1 : -1
		@album.add_or_update_evaluation(:album_votes, value, current_user)
		respond_to :html, :js
	end

	def index
		@albums = current_user.albums
	end

	def show
		if current_user == @album.user
			@songs = @album.songs
		else
			@songs = Song.where(:album_id => @album.id, :active => true)
		end

		@commentable = @album
		@comments = @commentable.comments
		@comment = Comment.new
	end

	def new
		@album = current_user.albums.build
	end

	def edit
	end

	def create
		@album = current_user.albums.build(params[:album])

		if @album.save
			 redirect_to @album, notice: 'You have successfully created an Album, you can add songs to the album below.'
		else
			 render action: "new" 
		end
	end

	def update
		if @album.update_attributes(params[:album])
			 redirect_to @album, notice: 'Album was successfully updated.'
		else
			 render action: "edit"
		end
	end

	def destroy
		@album.destroy
		redirect_to albums_url, notice: 'Album was deleted successfully.'
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/shared/_profile.html.haml
%ul.thumbnails
	-if @albums.each do |album| 
		%li.span2
			= link_to image_tag(album.cover.url(:large)), album, :class => "thumbnail", "data-original-title" => "#{album.name}", "data-content" => "<p>#{truncate(album.description, length: 200, seperator: ' ')}</p>", "data-trigger" => "hover", :rel => "popover"
	-end.empty?
		-show_msg = true
-if show_msg ==  true
	.alert.alert-info
		You don't have any albums yet, click on 
		= button_link "plus", "New Album", new_album_path, "btn-success btn-mini"
		to get started!

app/views/albums/shared/_vote.html.haml
%h6 Rate this album
.btn-toolbar
	-if current_user
		.btn-group
			= link_to "<i class='icon-heart'></i> #{pluralize(@album.reputation_value_for(:album_votes).to_i, "vote")}".html_safe, "#/", class: "btn btn-info disabled"
			-if current_user && current_user.voted_for?(@album)
				%span.btn.disabled Thanks!
		.btn-group
			= link_to "<i class='icon-thumbs-up icon-large'></i> Like".html_safe, vote_album_path(@album, type: "up"), :class => "btn btn-success", action: :vote, remote: :true
			= link_to "<i class='icon-thumbs-down icon-large'></i>".html_safe, vote_album_path(@album, type: "down"), :class => "btn btn-inverse", action: :vote, remote: :true
	-else
		.btn-group
			%span.btn.btn-info
				%i.icon-heart
				= pluralize(@album.reputation_value_for(:album_votes).to_i, "vote").html_safe
		.btn-group

			= link_to "Sign in to vote!".html_safe, new_user_session_path, :class => "btn btn-inverse"

app/views/albums/shared/_vote_thanks.html.haml
%h6 Rate this album
.btn-toolbar
	-if current_user
		.btn-group
			= link_to "<i class='icon-heart'></i> #{pluralize(@album.reputation_value_for(:album_votes).to_i, "vote")}".html_safe, "#/", class: "btn btn-info disabled"
			%span.btn.disabled Thanks!