config/routes.rb
Moza::Application.routes.draw do

  root :to => "welcome#index"
  devise_for :users, :skip => [:sessions], :controllers => { :registrations => :user_registrations }

  resources :users, :only => [:show, :index]

  resources :users do 

    member do
      get :following, :followers
    end

    resources :comments

  end

  as :user do
    get "account-artist" => "users#artist",            :as => :account_type_artist
    get "account-fan"    => "users#fan",               :as => :account_type_fan
    get 'account-type'   => 'users#type',              :as => :account_type
    get 'signin'         => 'devise/sessions#new',     :as => :new_user_session
    post 'signin'        => 'devise/sessions#create',  :as => :user_session
    delete 'signout'     => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :relationships, only: [:create, :destroy]
  
  resources :playlists do 
    resources :comments
    member { get :add_song_to }
  end
  
  resources :galleries do
    resources :comments
    resources :images
  end

  resources :images do
    resources :comments
  end

  namespace :admin do
    get 'home' => "pages#home"
  end

  resources :events do
    resources :comments
  end

  resources :videos do
    resources :comments
  end

  resources :albums do
    member { get :vote }

    resources :comments
    resources :songs
  end

  resources :songs do 
    member { 
      get :buy
      get :vote 
    }
  end
  
  resources :genres
  resources :articles

  match "discover" => "discover#index"
  match "discover/browse" => "discover#browse"
  match 'restricted' => "exceptions#restricted", :as => :restricted
  match 'buy/song/paypal' => "pages#paypal", :as => :paypal

end

app/models/video.rb
class Video < ActiveRecord::Base
    belongs_to :user
    attr_accessible :active, :description, :name, :youtube_url, :item
    has_many :comments, as: :commentable, :dependent => :destroy

    has_attached_file :item, :styles => { 
      :medium => { :geometry => "640x480", :format => 'flv' },
      :thumb => { :geometry => "640x480#", :format => 'jpg', :time => 10 }
    }, :processors => [:ffmpeg],
    :hash_secret => "Octo__NINJ@___^!",
    :url => "/:class/:id/:style/:hash.:extension",
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml"
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = current_user.videos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    # Comments
    @commentable = @video
    @comments = @commentable.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = current_user.videos.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = current_user.videos.build(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.haml
= simple_form_for @video, :html => { :class => 'form-vertical' }, :defaults => { :input_html => {:class => "input-block-level"} } do |f|
  = f.error_notification
  = f.input :name
  .row
    .span3
      = f.input :item, :input_html => { :class => "span4" }
    .span4
      = f.input :youtube_url, :input_html => { :class => "span4" }
  = f.input :description, :input_html => { :rows => 5}
  = f.label :active
  .btn-group{"data-toggle"=>"buttons-radio"}
    -if @video.active?
      %label.btn.btn-inverse.btn-large.active{:for=>"video_active"} 
        %i.icon-eye-open
        Active
    -else
      %label.btn.btn-inverse.btn-large{:for=>"video_active"} 
        %i.icon-eye-open
        Active

    -if !@video.active?
      %label.btn.btn-inverse.btn-large.active{:for=>"video_unactive"} 
        %i.icon-eye-close
        Hidden
    -else
      %label.btn.btn-inverse.btn-large{:for=>"video_unactive"} 
        %i.icon-eye-close
        Hidden

  = f.hint :active
  %input{:type=>"checkbox", :id=>"video_active", :name=>"video[active]", :value=>"1", :style=>"display:none"}
  %input{:type=>"checkbox", :id=>"video_unactive", :name=>"video[active]", :value=>"0", :style=>"display:none"}

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), videos_path, :class => 'btn'

app/views/videos/_video.html.haml
%li{ :class => "#{span}" }
  = link_to image_tag(video.item.url(:thumb)), video, class: :thumbnail, rel: :tooltip, title: video.name

app/views/videos/edit.html.haml
= bootstrap_page_header "Edit Video", "#{@video.name}" 
.row
	.span8.offset4
		.well
			= render 'form'
	.span4
		= link_to "Delete Video", video_path(@video), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-large btn-danger'

app/views/videos/index.html.haml
= bootstrap_page_header "Your Videos", "Share your videos with ease!" 

.row
  .span12
    .btn-group
      = button_link "plus", "New Video", new_video_path, "btn-success"
    %hr 
    .drop-zone
      %strong
        %i.icon-plus-sign 
        Drop a video here
      %p to learn more about drag and drop uploads, click here.
    %ul.thumbnails
      -if @videos.each do |video| 
        %li.span3
          = link_to image_tag(video.item.url(:thumb)), video, class: :thumbnail, rel: :tooltip, title: video.name
      -end.empty?
        -show_msg = true
    -if show_msg ==  true
      .alert.alert-info
        You don't have any videos yet, click on 
        = button_link "plus", "New Video", new_video_path, "btn-success btn-mini"
        to get started!
  .span4.omega
    %h4
      %i.icon-umbrella
      Welcome to the video manager, we make it pretty easy and fun to manage your videos.
    %hr
    %p
      %i.icon-arrow-right
      The first video will appear as the featured video on your profile.
    %hr
    %p
      %i.icon-move
      You can drag and drop your videos to arrage the order they appear on your profile.

app/views/videos/new.html.haml
= bootstrap_page_header "New Video", nil 

.row
	.span8.offset4
		.well
			= render 'form'

app/views/videos/show.html.haml
= bootstrap_page_header "#{@video.name}"
.row
  .span10.offset3
    .well.well-small.black
      -if @video.youtube_url.empty?
        %video.video-js.vjs-default-skin{:controls => "", "data-setup" => "{}", :height => "330", :poster => "#{@video.item.url(:thumb)}", :preload => "auto", :width => "100%"}
          %source{:src => @video.item.url, :type => "video/mp4"}
      -else 
        %iframe{:allowfullscreen => "", :frameborder => "0", :height => "330", :src => "http://www.youtube.com/embed/#{parse_youtube(@video.youtube_url)}", :width => "100%" }
    %hr.d
    .row
      .span2
        = link_to image_tag(@video.user.profile_photo.url(:large)), @video.user, :class => "thumbnail"
      .span8
        .well
          %h1
            = @video.user.username
            %small= @video.user.full_name

          %h6 Description
          %p= @video.description
    %h4
      #{@video.user.username}'s Videos
    %hr.d
    %ul.thumbnails
      = render @video.user.videos, :span => "span2"
    %h3 
      %i.icon-comments-alt
      Comments
    %hr
    =render 'comments/comments'
    =render 'comments/form'