config/routes.rb
Moza::Application.routes.draw do

  root :to => "welcome#index"
  devise_for :users, :skip => [:sessions], :controllers => { :registrations => :user_registrations }

  resources :users, :only => [:show, :index]

  resources :users do 

    member do
      get :following, :followers
    end

    resources :comments

  end

  as :user do
    get "account-artist" => "users#artist",            :as => :account_type_artist
    get "account-fan"    => "users#fan",               :as => :account_type_fan
    get 'account-type'   => 'users#type',              :as => :account_type
    get 'signin'         => 'devise/sessions#new',     :as => :new_user_session
    post 'signin'        => 'devise/sessions#create',  :as => :user_session
    delete 'signout'     => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :relationships, only: [:create, :destroy]
  
  resources :playlists do 
    resources :comments
    member { get :add_song_to }
  end
  
  resources :galleries do
    resources :comments
    resources :images
  end

  resources :images do
    resources :comments
  end

  namespace :admin do
    get 'home' => "pages#home"
  end

  resources :events do
    resources :comments
  end

  resources :videos do
    resources :comments
  end

  resources :albums do
    member { get :vote }

    resources :comments
    resources :songs
  end

  resources :songs do 
    member { 
      get :buy
      get :vote 
    }
  end
  
  resources :genres
  resources :articles

  match "discover" => "discover#index"
  match "discover/browse" => "discover#browse"
  match 'restricted' => "exceptions#restricted", :as => :restricted
  match 'buy/song/paypal' => "pages#paypal", :as => :paypal

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :songs
	has_many :comments, as: :commentable, :dependent => :destroy
	attr_accessible :name, :position
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def add_song_to
    song_id = params[:song_id]
    playlist_id = params[:playlist_id]
    playlist = Playlist.find(playlist_id)

    if current_user.id == playlist.user_id
      ptrack = PlaylistsSongs.new(:song_id => song_id, :playlist_id => playlist_id)
    end

    ptrack.save
    
    respond_to :html, :js

  end

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @playlists }
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @playlist = Playlist.find(params[:id])
    @songs = @playlist.songs

    @commentable = @playlist
    @comments = @commentable.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/new
  # GET /playlists/new.json
  def new
    @playlist = current_user.playlists.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = current_user.playlists.build(params[:playlist])

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render json: @playlist, status: :created, location: @playlist }
      else
        format.html { render action: "new" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /playlists/1
  # PUT /playlists/1.json
  def update
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      if @playlist.update_attributes(params[:playlist])
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.haml
= simple_form_for(@playlist, :defaults => { :input_html => {:class => "input-block-level"} }) do |f|
  = f.input :name
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), playlists_path, :class => 'btn'

app/views/playlists/_row.html.haml
= content_tag_for(:div, @playlists, :class => "row") do |playlist|
  .span6
    %h2
      = link_to playlist.name, playlist
    %p
      = button_link "move", nil, nil, "btn-inverse btn-mini"
      = button_link "edit", "Edit Details", edit_playlist_path(playlist), "btn-warning btn-mini"
  .span3
    %h6 Views
    %p 3,324
  .span3
    %h6 Total Plays
    %p 20
  .span12
    %hr.d

app/views/playlists/add_song_to.js.erb
$('span.add_song_to_playlist_<%= params[:song_id] %>').html("<%= escape_javascript(render('playlists/shared/after_add')) %>");

app/views/playlists/edit.html.haml
= bootstrap_page_header "Edit Playlist", "#{@playlist.name}" 
.row
	.span8.offset4
		.well
			= render 'form'
	.span4
		= link_to "Delete Playlist", playlist_path(@playlist), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-large btn-danger'

app/views/playlists/index.html.haml
= bootstrap_page_header "Your Playlists", "Create, share and listen to your favorite music, for free!" 

.row
  .span12
    = button_link "plus", "New Playlist", new_playlist_path, "btn-success"
    %hr
    %table.table.table-striped.table-bordered
      %thead
        %tr
          %th{:width => "70%"} Event
          %th{:width => "30%"} Actions
      %tbody
        - @playlists.each do |playlist|
          %tr
            %td= link_to "#{playlist.name}", playlist
            %td
              = button_link "edit", "Edit", edit_playlist_path(playlist), "btn-warning btn-mini"
              = button_link "eye-open", "View", playlist, "btn-info btn-mini"
              = button_link "share", "Share", playlist, "btn-inverse btn-mini"
  .span4

    %h4
      %i.icon-umbrella
      Welcome to the playlist manager, we make it pretty easy and fun to manage your playlists.
    %hr
    %p
      %i.icon-arrow-right
      The first playlist will appear as the featured playlist on your profile. 
    %hr
    %p
      %i.icon-move
      You can drag and drop your playlists to arrage the order they appear on your profile.

app/views/playlists/new.html.haml
= bootstrap_page_header "New Playlist", nil 
.row
	.span8.offset4
		.well
			= render 'form'
	.span4

		%p.lead New Playlist

		%hr

		%p
			%strong If this is your first playlist on Mozapolis these tips may come in handy!
		%p 
			You can add any song to any playlist and share it instantly just look for the 
			= button_link "share", "Share", nil, "btn-mini btn-inverse" 
			button!
		%hr.d
		%p You can edit this text in Admin > Blocks > Albums > New Album Info

app/views/playlists/show.html.haml
= bootstrap_page_header "#{@playlist.name}", "Playlist by #{icon_link(:user,@playlist.user.username, @playlist.user)}"

.row
	.span8
		=render "songs/row"
	.span8
		%h3 
			%i.icon-comments-alt
			Comments
		%hr
		=render 'comments/comments'
		=render 'comments/form'